services:
  db:
    image: postgis/postgis:latest
    env_file:
      - docker/local/python.env
      - .env
    ports:
      - "5433:5432"
  web:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    image: tripwix/python
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: tripwix_backend.settings.local
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - docker/local/python.env
      - .env
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: celery -A tripwix_backend worker --loglevel=debug
    volumes:
      - .:/code
    depends_on:
      - redis
    env_file:
      - docker/local/python.env
      - .env
  beat:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    command: celery -A tripwix_backend beat --loglevel=debug
    depends_on:
      - redis
    env_file:
      - docker/local/python.env
      - .env
  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - redis