# Generated by Django 4.2.1 on 2023-08-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='EmailDefinitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(editable=False, max_length=250, verbose_name='Name')),
                ('module_path', models.CharField(editable=False, max_length=250, unique=True, verbose_name='Module Path')),
                ('data', models.JSONField(blank=True, null=True)),
                (
                    'allow_send',
                    models.BooleanField(
                        default=True, help_text='Designate if this email can be sent out.', verbose_name='Allow sending this type of emails?'
                    ),
                ),
                ('last_sent_email_ts', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Latest email date')),
                ('last_sent_email_to', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Latest email')),
            ],
            options={
                'verbose_name': 'Email Definition',
                'verbose_name_plural': 'Email Definitions',
            },
        ),
        migrations.CreateModel(
            name='EmailDefinitionTranslationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('lang', models.CharField(choices=[('en', 'English'), ('pt', 'Portuguese'), ('es', 'Spanish')], max_length=32)),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                (
                    'email_definition',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='def_email.emaildefinitionmodel'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['-is_active', 'lang'],
                'unique_together': {('email_definition', 'lang')},
            },
        ),
    ]
