# Generated by Django 4.2.14 on 2024-09-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('def_email', '0003_alter_emaildefinitiontranslationmodel_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildefinitiontranslationmodel',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('pt', 'Portuguese')], max_length=32),
        ),
    ]
