# Generated by Django 5.0.6 on 2024-09-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['item_order'], 'verbose_name': 'Q&A', 'verbose_name_plural': 'Q&A'},
        ),
    ]
