# Generated by Django 4.2.14 on 2024-09-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_alter_faq_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='is_active',
        ),
    ]
