# Generated by Django 4.2.5 on 2023-09-12 06:41

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='Internal Handle')),
                ('detail_type', models.CharField(choices=[('text', 'Text'), ('trans_text', 'Translatable Text'), ('boolean', 'Boolean'), ('option', 'Option'), ('options', 'Options'), ('date', 'Date'), ('time', 'Time'), ('number', 'Number'), ('integer', 'Integer'), ('color', 'Color'), ('description', 'Description'), ('trans_description', 'Translatable Description'), ('integer_options', 'Integer Options'), ('rating', 'Rating'), ('videos', 'Videos'), ('image', 'Image'), ('360_image', 'Image 360'), ('integer_sum', 'Integer with Sum')], max_length=20, verbose_name='detail type')),
                ('sort_order', models.SmallIntegerField(default=0, verbose_name='order')),
                ('unit', models.CharField(blank=True, help_text='units used by type field', max_length=10, verbose_name='unit')),
                ('help_text', models.CharField(blank=True, max_length=250, verbose_name='help text')),
                ('initial_text_value', models.CharField(blank=True, max_length=128, verbose_name='default text')),
                ('initial_bool_value', models.BooleanField(blank=True, default=False, verbose_name='default boolean')),
                ('initial_description_value', models.TextField(blank=True, verbose_name='default description')),
                ('initial_number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='default number decimal')),
                ('initial_integer_value', models.IntegerField(blank=True, default=0, null=True, verbose_name='default number')),
                ('initial_date_value', models.DateField(blank=True, null=True, verbose_name='default date')),
                ('initial_time_value', models.TimeField(blank=True, null=True, verbose_name='default time')),
                ('admin_related_opts_permissions', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Admin related options permissions')),
                ('in_search', models.BooleanField(default=False, help_text='Allow this detail to be searched', verbose_name='Searchable')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DetailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Url / Handle')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon')),
                ('item_o', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Detail Category',
                'verbose_name_plural': 'Detail Categories',
                'ordering': ('item_o',),
            },
        ),
        migrations.CreateModel(
            name='DetailCategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(verbose_name='Url / Handle')),
                ('item_o', models.IntegerField(default=0, verbose_name='Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='properties.detailcategory')),
            ],
            options={
                'verbose_name': 'Detail Category Section',
                'verbose_name_plural': 'Detail Category Sections',
                'ordering': ('category', 'item_o'),
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DetailOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='slug')),
                ('sort_order', models.SmallIntegerField(blank=True, default=0, verbose_name='order')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='properties.detail')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['sort_order'],
                'unique_together': {('detail', 'slug')},
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='property_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertygroup'),
        ),
        migrations.CreateModel(
            name='PropertyGroupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='is required')),
                ('is_filter', models.BooleanField(default=False, verbose_name='is filter')),
                ('sort_order', models.SmallIntegerField(default=0, verbose_name='order')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.detail')),
                ('property_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertygroup')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.detailcategorysection')),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'ordering': ['section', 'sort_order'],
                'unique_together': {('property_group', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='PropertyDetailValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.CharField(blank=True, max_length=128, verbose_name='text')),
                ('bool_value', models.BooleanField(blank=True, default=False, verbose_name='boolean')),
                ('description_value', models.TextField(blank=True, verbose_name='description')),
                ('number_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='number decimal')),
                ('integer_value', models.IntegerField(blank=True, default=0, null=True, verbose_name='number')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='date')),
                ('time_value', models.TimeField(blank=True, null=True, verbose_name='time')),
                ('detail_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_value', to='properties.detailoption')),
                ('detail_options', models.ManyToManyField(blank=True, related_name='options_value', to='properties.detailoption')),
                ('property_group_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertygroupdetails')),
                ('property_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_values', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Detail Value',
                'verbose_name_plural': 'Property Detail Values',
                'db_table': 'property_detail_values',
                'ordering': ['property_group_detail'],
            },
        ),
    ]
