# Generated by Django 4.2.5 on 2023-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_detail_detailcategory_detailcategorysection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='details',
            field=models.ManyToManyField(blank=True, null=True, through='properties.PropertyDetailValues', to='properties.propertygroupdetails'),
        ),
        migrations.AddField(
            model_name='propertygroup',
            name='details',
            field=models.ManyToManyField(related_name='group', through='properties.PropertyGroupDetails', to='properties.detail'),
        ),
        migrations.AlterField(
            model_name='propertygroup',
            name='sale_type',
            field=models.CharField(choices=[('D', 'Default')], default='d', max_length=1, unique=True, verbose_name='Sale type'),
        ),
    ]
