# Generated by Django 4.2.5 on 2023-09-23 02:55

import django.db.models.deletion
import photologue.models
from django.db import migrations, models

import apps.media.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0013_alter_watermark_image'),
        ('properties', '0003_property_details_propertygroup_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMediaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=photologue.models.get_storage_path, verbose_name='image')),
                ('date_taken', models.DateTimeField(blank=True, help_text='Date image was taken; is obtained from the image EXIF data.', null=True, verbose_name='date taken')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='view count')),
                ('crop_from', models.CharField(blank=True, choices=[('top', 'Top'), ('right', 'Right'), ('bottom', 'Bottom'), ('left', 'Left'), ('center', 'Center (Default)')], default='center', max_length=10, verbose_name='crop from')),
                ('caption', models.CharField(blank=True, max_length=128, null=True, verbose_name='caption')),
                ('alt_text', models.CharField(blank=True, max_length=128, null=True, verbose_name='Alternative text')),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='photologue.photoeffect', verbose_name='effect')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'db_table': 'property_media_photo',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='photos',
            field=apps.media.fields.MediaPhotoField(blank=True, to='properties.propertymediaphoto'),
        ),
    ]
