# Generated by Django 4.2.6 on 2023-10-13 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_options_alter_country_options'),
        ('properties', '0004_propertymediaphoto_property_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('item_o',), 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertytypology',
            options={'ordering': ('name', 'item_o'), 'verbose_name': 'Typology', 'verbose_name_plural': 'Typologies'},
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='account_type',
            field=models.CharField(blank=True, choices=[('person', 'Person'), ('company', 'Company')], verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='company_legal_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'Whatsapp')], verbose_name='Preferred Contact Method'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Reservation Email 1'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Reservation Email 2'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='language',
            field=models.CharField(blank=True, max_length=20, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes 1'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='notes_2',
            field=models.TextField(blank=True, verbose_name='Contact Notes 2'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='onboarding_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Onboarding Contact'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='onboarding_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Onboarding Source'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Reservation Phone 1'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Reservation Phone 2'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State and Province'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Street Name and Number'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax ID'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='propertygroup',
            name='sale_type',
            field=models.CharField(choices=[('D', 'Default'), ('r', 'Rental')], default='d', max_length=1, unique=True, verbose_name='Sale type'),
        ),
    ]
