# Generated by Django 4.2.6 on 2023-10-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyownership',
            name='account_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Person', 'Person'), ('Company', 'Company')], verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reservation Phone 1'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='phone_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reservation Phone 2'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zip Code'),
        ),
    ]
