# Generated by Django 4.2.5 on 2023-10-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertyownership_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyownership',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes 1'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='notes_2',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Notes 2'),
        ),
    ]
