# Generated by Django 4.2.5 on 2023-10-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_propertyownership_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyownership',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Person', 'Person'), ('Company', 'Company')], null=True, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='company_legal_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'Whatsapp')], null=True, verbose_name='Preferred Contact Method'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='onboarding_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Onboarding Contact'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='onboarding_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Onboarding Source'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reservation Phone 1'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='phone_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reservation Phone 2'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State and Province'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Name and Number'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zip Code'),
        ),
    ]
