# Generated by Django 4.2.6 on 2023-10-22 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertymanager_remove_property_commission_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location', verbose_name='destination'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sublocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.sublocation', verbose_name='community'),
        ),
        migrations.AlterField(
            model_name='propertydetailvalues',
            name='text_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='text'),
        ),
        migrations.AlterUniqueTogether(
            name='propertydetailvalues',
            unique_together={('property_object', 'property_group_detail')},
        ),
    ]
