# Generated by Django 4.2.5 on 2023-10-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_location_alter_property_sublocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Leave blank to use the default property description.', max_length=255, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Leave blank to use the default property title.', max_length=155, verbose_name='SEO Title'),
        ),
    ]
