# Generated by Django 4.2.5 on 2023-10-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Leave blank to use the default property description.', max_length=500, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Leave blank to use the default property title.', max_length=500, verbose_name='SEO Title'),
        ),
    ]
