# Generated by Django 4.2.7 on 2023-11-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0012_alter_property_seo_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="standard_photos_synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="standard_photos_url",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="propertymediaphoto",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="image"),
        ),
    ]
