# Generated by Django 4.2.7 on 2023-11-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_standard_photos_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymediaphoto',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
    ]
