# Generated by Django 4.2.13 on 2024-05-20 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_propertymediaphoto_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Url / Handle')),
                ('item_o', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Amenity Category',
                'verbose_name_plural': 'Amenity Categories',
                'ordering': ('item_o',),
            },
        ),
        migrations.AlterModelOptions(
            name='propertymediaphoto',
            options={'ordering': ('order',), 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Url / Handle')),
                ('item_o', models.IntegerField(default=0, verbose_name='Order')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amenities', to='properties.amenitycategory')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ('item_o',),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='properties.amenity'),
        ),
    ]
