# Generated by Django 4.2.13 on 2024-05-23 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_amenitycategory_alter_propertymediaphoto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybedroomsconfig',
            name='bedroom_type',
        ),
        migrations.AddField(
            model_name='propertybedroomsconfig',
            name='division',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='properties.propertydivision',
                verbose_name='division',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydivision',
            name='name',
            field=models.CharField(default='nd', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PropertyBedroomsConfigType',
        ),
    ]
