# Generated by Django 4.2.13 on 2024-05-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_remove_propertybedroomsconfig_bedroom_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDivisionExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Division Extra',
                'verbose_name_plural': 'Division Extras',
            },
        ),
        migrations.AddField(
            model_name='propertydivision',
            name='extra',
            field=models.ManyToManyField(blank=True, null=True, to='properties.propertydivisionextra'),
        ),
    ]
