# Generated by Django 4.2.13 on 2024-05-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_propertydivisionextra_propertydivision_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybedroomsconfig',
            name='description',
        ),
    ]
