# Generated by Django 4.2.13 on 2024-06-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_remove_propertybedroomsconfig_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydivision',
            name='area',
        ),
    ]
