# Generated by Django 4.2.13 on 2024-06-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_remove_propertydivision_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('item_o',), 'permissions': (('can_publish_property', 'Can Publish Property'),), 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
