# Generated by Django 4.2.13 on 2024-07-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_alter_property_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='From (date)')),
                ('to_date', models.DateField(verbose_name='To (date)')),
                ('season', models.CharField(blank=True, choices=[('Low', 'Low'), ('Mid', 'Mid'), ('High', 'High'), ('Peak', 'Peak'), ('Other', 'Other'), ('Close', 'Close')], max_length=10, verbose_name='Season')),
                ('minimum_nights', models.PositiveIntegerField(verbose_name='Minimum Nights')),
                ('website_sales_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Website & Sales value')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'from_date', 'to_date')},
            },
        ),
    ]
