# Generated by Django 4.2.13 on 2024-07-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_detail_detail_type'),
        ('properties', '0021_rate'),
    ]

    operations = [
    ]
