# Generated by Django 4.2.13 on 2024-07-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_alter_property_options_alter_detail_detail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='initial_number_with_value_type_selector_value',
            field=models.CharField(choices=[('p', 'Percentage'), ('c', 'Currency Amount')], default='p', max_length=1, verbose_name='default number with value type selector'),
        ),
    ]
