# Generated by Django 4.2.13 on 2024-07-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_merge_0021_alter_detail_detail_type_0021_rate'),
        ('properties', '0023_detail_initial_number_with_value_type_selector_value'),
    ]

    operations = [
    ]
