# Generated by Django 4.2.14 on 2024-08-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_merge_20240704_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hostify_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
