# Generated by Django 4.2.14 on 2024-09-09 10:28

from django.db import migrations, models


def fix_onboarding_source(apps, schema_editor):
    PropertyOwnership = apps.get_model('properties', 'PropertyOwnership')
    for po in PropertyOwnership.objects.all():
        if not po.onboarding_source:
            continue
        if po.onboarding_source == 'Amb. Relations':
            po.onboarding_source = 'amb_relations'
        elif po.onboarding_source == 'Direct':
            po.onboarding_source = 'direct'
        else:
            po.onboarding_source = 'other'
        po.save()


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_property_hostify_id'),
    ]

    operations = [
        migrations.RunPython(fix_onboarding_source, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='propertyownership',
            name='onboarding_source',
            field=models.CharField(
                blank=True,
                choices=[('amb_relations', 'Amb. Relations'), ('direct', 'Direct'), ('other', 'Other')],
                max_length=13,
                null=True,
                verbose_name='Onboarding Source',
            ),
        ),
    ]
