# Generated by Django 4.2.14 on 2024-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_alter_propertyownership_onboarding_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyownership',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'Whatsapp')], null=True, verbose_name='Preferred Contact Method'),
        ),
    ]
