# Generated by Django 4.2.14 on 2024-09-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_alter_propertyownership_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyownership',
            options={'ordering': ('name',), 'verbose_name': 'Ownership', 'verbose_name_plural': 'Ownerships'},
        ),
        migrations.RemoveField(
            model_name='propertyownership',
            name='item_o',
        ),
    ]
