# Generated by Django 4.2.14 on 2024-09-27 10:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_alter_propertyownership_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRatingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='score')),
                ('testimonial', models.TextField(blank=True, verbose_name='testimonial')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('property_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='properties.property')),
            ],
        ),
    ]
