# Generated by Django 4.2.14 on 2024-10-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_propertyratingscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Default Price'),
        ),
    ]
