# Generated by Django 4.2.14 on 2024-09-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_propertyratingscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymediaphoto',
            name='is_synched',
            field=models.BooleanField(default=False),
        ),
    ]
