# Generated by Django 4.2.14 on 2024-09-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_propertyratingscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyownership',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reservation Phone 1'),
        ),
    ]
