# Generated by Django 4.2.14 on 2024-10-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_property_default_price'),
        ('properties', '0031_propertymediaphoto_is_synched'),
    ]

    operations = [
    ]
