# Generated by Django 4.2.14 on 2024-10-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_countryvatrate'),
        ('properties', '0032_alter_propertyownership_company_legal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanager',
            name='account_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='concierge_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Concierge Email'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='concierge_phone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Concierge Phone'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'Whatsapp')], null=True, verbose_name='Preferred Contact Method'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Reservation Email 1'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Reservation Email 2'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='language',
            field=models.CharField(blank=True, choices=[('en_us', 'en-us'), ('en_gb', 'en-gb'), ('pt_pt', 'pt-pt'), ('pt_br', 'pt-br'), ('es', 'es'), ('fr', 'fr'), ('it', 'it'), ('tr', 'tr'), ('other', 'Other')], max_length=5, null=True, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes 1'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='notes_2',
            field=models.TextField(blank=True, null=True, verbose_name='Contact Notes 2'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reservation Phone 1'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='phone_2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Reservation Phone 2'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='State and Province'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='street',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Street Name and Number'),
        ),
        migrations.AddField(
            model_name='propertymanager',
            name='zip_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zip Code'),
        ),
    ]
