# Generated by Django 4.2.14 on 2024-10-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_propertymanager_account_id_propertymanager_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanager',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
