# Generated by Django 4.2.14 on 2024-10-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_merge_20241001_1206'),
        ('properties', '0035_propertyownership_comments'),
    ]

    operations = [
    ]
