# Generated by Django 4.2.14 on 2024-10-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_merge_20241001_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='changes_to_sync',
            field=models.JSONField(blank=True, null=True, verbose_name='Changes to Sync'),
        ),
        migrations.AddField(
            model_name='property',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At'),
        ),
        migrations.AddField(
            model_name='property',
            name='last_synced_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Last Synced Payload'),
        ),
        migrations.AddField(
            model_name='property',
            name='ready_to_sync',
            field=models.BooleanField(default=False, verbose_name='Ready to Sync'),
        ),
        migrations.AddField(
            model_name='property',
            name='sync_status',
            field=models.CharField(choices=[('synced', 'Synced'), ('not_synced', 'Not Synced'), ('syncing', 'Syncing'), ('sync_failed', 'Sync Failed'), ('sync_pending', 'Sync Pending')], default='not_synced', max_length=12, verbose_name='Sync Status'),
        ),
    ]
