# Generated by Django 4.2.14 on 2024-10-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_property_changes_to_sync_property_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='needs_calendar_creation',
            field=models.BooleanField(default=False, verbose_name='Needs Calendar Creation'),
        ),
    ]
