# Generated by Django 4.2.14 on 2024-10-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_property_needs_calendar_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymanager',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Property Manager Email 1'),
        ),
        migrations.AlterField(
            model_name='propertymanager',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Property Manager Email 2'),
        ),
        migrations.AlterField(
            model_name='propertymanager',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Phone 1'),
        ),
        migrations.AlterField(
            model_name='propertymanager',
            name='phone_2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Phone 2'),
        ),
    ]
