# Generated by Django 4.2.14 on 2024-10-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_propertycategory_property_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Permit/Tax ID'),
        ),
    ]
