# Generated by Django 4.2.14 on 2024-10-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_property_tax_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tax_id',
        ),
    ]
