# Generated by Django 4.2.14 on 2024-11-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0043_set_last_synced_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Permit/Tax ID'),
        ),
    ]
