# Generated by Django 4.2.14 on 2024-11-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_property_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cir_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='number'),
        ),
        migrations.AddField(
            model_name='property',
            name='know_before_you_go',
            field=models.TextField(blank=True, null=True, verbose_name='Know Before You Go'),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_price_included',
            field=models.TextField(blank=True, null=True, verbose_name='Rental Price Included'),
        ),
        migrations.AddField(
            model_name='propertyratingscore',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='propertyratingscore',
            name='country',
            field=models.CharField(blank=True, max_length=30, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='propertyratingscore',
            name='state',
            field=models.CharField(blank=True, max_length=30, verbose_name='state'),
        ),
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='ambassadors/')),
                ('property_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambassadors', to='properties.property')),
            ],
        ),
    ]
