# Generated by Django 4.2.14 on 2024-11-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0045_property_cir_id_property_know_before_you_go_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_url',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='URL / Handle'),
        ),
        migrations.AddField(
            model_name='property',
            name='tagline',
            field=models.CharField(blank=True, help_text='Tagline for the property', max_length=50, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
