# Generated by Django 4.2.14 on 2024-11-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0046_property_property_url_property_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyratingscore',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='city'),
        ),
    ]
