# Generated by Django 4.2.14 on 2024-11-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0047_propertyratingscore_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyratingscore',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='name'),
        ),
    ]
