# Generated by Django 4.2.14 on 2024-11-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0048_alter_propertyratingscore_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambassador',
            name='property_object',
        ),
        migrations.AddField(
            model_name='property',
            name='ambassador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.ambassador'),
        ),
    ]
