# Generated by Django 4.2.14 on 2024-11-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0049_remove_ambassador_property_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='permit_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='number'),
        ),
    ]
