# Generated by Django 4.2.14 on 2024-11-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0051_auto_20241113_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cir_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cir_id'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='permit_id',
        ),
    ]
