# Generated by Django 4.2.14 on 2024-11-15 11:20

from django.db import migrations
from django.utils.text import slugify


def update_property_urls(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    for property_instance in Property.objects.all():
        parts = ['luxury-home-rentals']
        if property_instance.location and property_instance.location.name:
            parts.append(slugify(property_instance.location.name))
        detail_tagline = property_instance.tagline
        if detail_tagline:
            parts.append(slugify(detail_tagline))
        parts.append(str(property_instance.id))
        property_instance.property_url = '/'.join(parts)
        property_instance.save(update_fields=['property_url'])
        
class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0053_alter_ambassador_description_alter_ambassador_photo'),
    ]

    operations = [migrations.RunPython(update_property_urls , reverse_code=migrations.RunPython.noop),
                  ]
