# Generated by Django 4.2.14 on 2024-11-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0055_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('tax_object', models.JSONField(blank=True, null=True, verbose_name='Tax Object')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='properties.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
