# Generated by Django 4.2.14 on 2024-11-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0057_currency_alter_propertytax_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
