# Generated by Django 4.2.14 on 2024-11-29 09:12

from django.db import migrations, models
from django.utils.text import slugify


def update_property_slugs(apps, schema_editor):
    Property = apps.get_model('properties', 'Property')
    for property_instance in Property.objects.all():
        parts = []
        if property_instance.location and property_instance.location.name:
            parts.append(slugify(property_instance.location.name))
        detail_tagline = property_instance.tagline
        if detail_tagline:
            parts.append(slugify(detail_tagline))
        parts.append(str(property_instance.reference))
        property_instance.slug = '/'.join(parts)
        property_instance.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0058_delete_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_url',
        ),
        migrations.RunPython(update_property_slugs, reverse_code=migrations.RunPython.noop),
    ]
