# Generated by Django 4.2.14 on 2024-11-29 09:12

from datetime import date, timedelta

from django.db import migrations


def update_property_calendars(apps, schema_editor):
    from apps.properties.utils import get_property_calendars

    Property = apps.get_model('properties', 'Property')
    PropertyCalendar = apps.get_model('hostify', 'PropertyCalendar')
    for property_instance in Property.objects.filter(hostify_id__isnull=False):
        start_date = date.today()
        end_date = date.today() + timedelta(days=365)
        calendars = get_property_calendars(property_instance.hostify_id, start_date, end_date)
        PropertyCalendar.objects.filter(property=property_instance).delete()
        calendar_obj_list = [PropertyCalendar(**calendar, property_id=property_instance.id) for calendar in calendars]
        PropertyCalendar.objects.bulk_create(calendar_obj_list)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0059_remove_property_property_url'),
    ]

    operations = [
        migrations.RunPython(update_property_calendars, reverse_code=migrations.RunPython.noop),
    ]
