# Generated by Django 4.2.14 on 2024-12-10 12:26

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0060_update_property_calendars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('MXN', 'Mexican Peso')], max_length=3, primary_key=True, serialize=False, unique=True)),
                ('symbol', models.CharField(max_length=5)),
                ('position', models.CharField(choices=[('before', 'Before'), ('after', 'After')], default='before', max_length=10)),
                ('rate', models.DecimalField(decimal_places=10, default=Decimal('1.0'), help_text='Exchange rate relative to USD.', max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currency',
            },
        ),
    ]
