# Generated by Django 4.2.14 on 2024-12-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0061_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('item_o',), 'permissions': (('can_sync_property', 'Can Sync Property'), ('can_publish_property', 'Can Publish Property'), ('can_change_vat_rate', 'Can Change Property VAT Rate')), 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
