# Generated by Django 4.2.14 on 2025-02-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0063_propertyamenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyamenity',
            name='is_active',
        ),
    ]
