# Generated by Django 4.2.14 on 2025-02-03 09:49

from django.db import migrations


def populate_property_amenity(apps, schema_editor):
    PropertyAmenity = apps.get_model('properties', 'PropertyAmenity')
    Property = apps.get_model('properties', 'Property')

    for property in Property.objects.prefetch_related('amenities').all():
        amenities_list = [PropertyAmenity(property=property, amenity=amenity) for amenity in property.amenities.all()]

        PropertyAmenity.objects.bulk_create(amenities_list)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0064_remove_propertyamenity_is_active'),
    ]

    operations = [migrations.RunPython(populate_property_amenity, reverse_code=migrations.RunPython.noop)]
