# Generated by Django 4.2.14 on 2025-02-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0065_populate_property_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Click to select active amenities.<br/>Light blue means they will be seen in the Website.<br/>Delete by selecting one then pressing Backspace.<br/>', to='properties.amenity'),
        ),
    ]
