# Generated by Django 4.2.14 on 2025-02-15 17:04

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0066_alter_property_amenities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='default_price_usd',
            new_name='default_price_eur',
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0'), help_text='Exchange rate relative to EUR.', max_digits=20),
        ),
        migrations.AlterField(
            model_name='rate',
            name='website_sales_value',
            field=models.DecimalField(decimal_places=2, help_text='Value in Euros (€)', max_digits=10, verbose_name='Website & Sales value'),
        ),
    ]
