# Generated by Django 4.2.14 on 2025-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0067_rename_default_price_usd_property_default_price_eur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='default_price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Default Price in EUR (€)'),
        ),
    ]
