# Generated by Django 4.2.14 on 2025-02-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0069_property_property_item_o_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-item_o',), 'permissions': (('can_sync_property', 'Can Sync Property'), ('can_publish_property', 'Can Publish Property'), ('can_change_vat_rate', 'Can Change Property VAT Rate')), 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='cir_id',
        ),
    ]
