# Generated by Django 4.2.14 on 2025-02-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0070_alter_property_options_remove_property_cir_id_and_more'),
    ]

    operations = []
