# Generated by Django 4.2.14 on 2025-02-25 16:55

from django.db import migrations


def delete_property_amenity(apps, schema_editor):
    PropertyAmenity = apps.get_model('properties', 'PropertyAmenity')
    PropertyAmenity.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0071_property_tax_id'),
    ]

    operations = [
        migrations.RunPython(delete_property_amenity, reverse_code=migrations.RunPython.noop),
    ]
