# Generated by Django 4.2.19 on 2025-05-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0072_delete_property_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, help_text='Click to select active amenities.<br/>Light blue means they will be seen in the Website.<br/>Delete by selecting one then pressing Backspace.<br/>', through='properties.PropertyAmenity', to='properties.amenity'),
        ),
    ]
