# Generated by Django 4.2.14 on 2024-08-20 04:59

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='content',
            name='content_hashid_idx',
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['app_model', 'object_id'], name='content_con_app_mod_4046e8_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='content_con_i18n_492dbf_gin'),
        ),
    ]
