# Generated by Django 4.2.14 on 2024-08-23 00:55

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_content_content_hashid_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='content',
            name='content_con_app_mod_4046e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='content_con_i18n_492dbf_gin',
        ),
        migrations.AddIndex(
            model_name='content',
            index=django.contrib.postgres.indexes.HashIndex(fields=['id'], name='content_hashid_idx'),
        ),
    ]
