# Generated by Django 4.2.14 on 2024-10-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_form_id_lead_notes_lead_src_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('number_of_bedrooms', models.PositiveIntegerField()),
                ('number_of_guests', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('is_travel_date_flexible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
            },
        ),
    ]
