# Generated by Django 4.2.14 on 2024-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='property_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
