# Generated by Django 4.2.14 on 2024-10-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_inquiry_property_id_inquiry_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='how_can_we_help_extra_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='where_heard_about_us_extra_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
