# Generated by Django 4.2.14 on 2024-10-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_how_can_we_help_extra_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='newsletter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
