# Generated by Django 4.2.14 on 2024-10-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='how_can_we_help',
            field=models.CharField(blank=True, choices=[('villa_rental', "I'm interested in a Villa Rental"), ('property_management', 'I would like to know more about property management'), ('homeowner_partner', 'I am a homeowner and would like to partner with you'), ('travel_agent_inquiry', 'I am a travel agent with an inquiry'), ('book_services', 'Would like to book extra services and/or activities'), ('press_member_info', 'I am a Press Member and desire information on the company'), ('other', 'Other (specify the service)')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='where_heard_about_us',
            field=models.CharField(blank=True, choices=[('traveled_before', 'I have traveled with you before'), ('word_of_mouth', 'Word of mouth'), ('referral', 'Referral'), ('search_engine', 'Search (Google, Bing, etc)'), ('online_advertising', 'Online Advertising'), ('influencer', 'Influencer'), ('magazine_advert', 'Advert on Magazine'), ('event', 'Event'), ('social_media', 'Social Media'), ('travel_agency', 'Travel Agency'), ('other', 'Other (please specify)')], max_length=255, null=True),
        ),
    ]
