# Generated by Django 4.2.14 on 2025-01-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_how_can_we_help_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='smsMarketing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
