# Generated by Django 4.2.14 on 2025-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_smsmarketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='smsMarketing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
