# Generated by Django 4.2.14 on 2025-02-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_inquiry_smsmarketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
