# Generated by Django 4.2.14 on 2025-02-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_property_name_lead_property_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
