# Generated by Django 4.2.14 on 2025-02-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_property_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='property_code',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='property_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='property_url',
        ),
    ]
