# Generated by Django 4.2.14 on 2024-10-08 11:49

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='whats_included',
        ),
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True, verbose_name='Url / Handle'),
        ),
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True, verbose_name='Url / Handle'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 8, 11, 49, 50, 686147, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='experiences.experience')),
            ],
            options={
                'verbose_name': 'Inclusion',
                'verbose_name_plural': 'Inclusions',
            },
        ),
    ]
