# Generated by Django 4.2.14 on 2024-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_remove_wishlist_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='inclusion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
