# Generated by Django 4.2.14 on 2024-10-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_inclusion_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='destination',
        ),
    ]
