# Generated by Django 4.2.14 on 2025-03-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_wishlistexperience_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='title',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='activities',
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='experience',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='experiences.activity'),
        ),
    ]
