# Generated by Django 4.2.1 on 2023-08-09 16:25

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Handle')),
                ('is_internal', models.BooleanField(default=False, verbose_name='is internal')),
                ('i18n', apps.core.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'Collection Type',
                'verbose_name_plural': 'Collection Types',
            },
        ),
        migrations.CreateModel(
            name='CollectionTypeComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_o', models.IntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Collection component',
                'verbose_name_plural': 'Collection components',
                'ordering': ['item_o'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Handle')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('i18n', apps.core.fields.TranslationField(fields=('name', 'description'), required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
            },
        ),
        migrations.CreateModel(
            name='ComponentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                (
                    'field_type',
                    models.CharField(
                        choices=[
                            ('text', 'text'),
                            ('description', 'description'),
                            ('phone', 'phone number'),
                            ('email', 'email'),
                            ('color', 'color'),
                            ('option', 'option'),
                            ('date', 'date'),
                            ('time', 'time'),
                            ('datetime', 'datetime'),
                            ('number', 'number'),
                            ('boolean', 'boolean'),
                            ('integer', 'integer'),
                            ('app', 'app'),
                            ('cta', 'cta'),
                            ('json_field', 'json field'),
                            ('image', 'image'),
                            ('file', 'file'),
                        ],
                        max_length=20,
                        verbose_name='field type',
                    ),
                ),
                ('unit', models.CharField(blank=True, default='', max_length=10, verbose_name='unit')),
                ('app_selectable', models.BooleanField(default=True, verbose_name='Is Selectable')),
                ('i18n', apps.core.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                (
                    'app_model',
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
                ),
            ],
            options={
                'verbose_name': 'Component Field',
                'verbose_name_plural': 'Component Fields',
            },
        ),
        migrations.CreateModel(
            name='ComponentFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Handle')),
                ('item_o', models.IntegerField(default=0, verbose_name='Sort order')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is required')),
                ('is_translatable', models.BooleanField(default=False, verbose_name='Is translatable')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='Is multiple')),
                ('i18n', apps.core.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                (
                    'component',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_fields', to='components.component'),
                ),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='components.componentfield')),
            ],
            options={
                'verbose_name': 'component Field',
                'verbose_name_plural': 'component Fields',
                'ordering': ['item_o'],
            },
        ),
        migrations.CreateModel(
            name='ComponentFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Handle')),
                ('i18n', apps.core.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='components.componentfield')),
            ],
            options={
                'verbose_name': 'Component Field Option',
                'verbose_name_plural': 'Component Field Options',
            },
        ),
        migrations.AddIndex(
            model_name='component',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='components__i18n_208e4b_gin'),
        ),
        migrations.AddField(
            model_name='collectiontypecomponents',
            name='collection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='components.collectiontype'),
        ),
        migrations.AddField(
            model_name='collectiontypecomponents',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_types', to='components.component'),
        ),
        migrations.AddIndex(
            model_name='collectiontype',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='components__i18n_205db3_gin'),
        ),
        migrations.AddIndex(
            model_name='componentfields',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='components__i18n_871113_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='componentfields',
            unique_together={('component', 'slug')},
        ),
        migrations.AddIndex(
            model_name='componentfieldoption',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='components__i18n_8ab27f_gin'),
        ),
        migrations.AddIndex(
            model_name='componentfield',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='components__i18n_85756d_gin'),
        ),
    ]
