# Generated by Django 4.2.4 on 2023-08-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='City name')),
                ('slug', models.SlugField(unique=True, verbose_name='Url / Handle')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Citys',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha2', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ISO alpha-2')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('numcode', models.PositiveSmallIntegerField(null=True, verbose_name='ISO numeric')),
                ('alpha3', models.CharField(help_text='ISO 3166-1 Alpha-3 Code', max_length=3, unique=True)),
                ('phone', models.CharField(help_text='Phone Indicative', max_length=3)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countrys',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='District Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Url / Handle')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Region name')),
                ('slug', models.SlugField(unique=True, verbose_name='Url / Handle')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Local name')),
                ('slug', models.SlugField(unique=True, verbose_name='Url / Handle')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether the location appear in the back and front office', verbose_name='active')),
                ('active_sublocations', models.BooleanField(default=True, help_text='Designates whether the sublocations of this location appear in the front office', verbose_name='active sublocations')),
                ('sort_order', models.SmallIntegerField(default=0, verbose_name='order')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ('sort_order',),
                'unique_together': {('slug', 'city', 'district', 'region', 'country')},
            },
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sub-Local name')),
                ('slug', models.SlugField(verbose_name='Url / Handle')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
            options={
                'verbose_name': 'Sub location',
                'verbose_name_plural': 'Sub locations',
                'ordering': ('name',),
                'unique_together': {('slug', 'location')},
            },
        ),
    ]
