# Generated by Django 4.2.6 on 2023-10-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_city_options_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('sort_order',), 'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='sublocation',
            options={'ordering': ('name',), 'verbose_name': 'Community', 'verbose_name_plural': 'Community'},
        ),
    ]
