# Generated by Django 4.2.5 on 2023-11-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_options_alter_sublocation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublocation',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='Url / Handle'),
        ),
    ]
