# Generated by Django 4.2.13 on 2024-07-04 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_sublocation_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryVatRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='VAT Name')),
                ('description', models.TextField(blank=True, verbose_name='VAT Description')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Value Added Tax Rate', max_digits=5, verbose_name='Rate')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_rates', to='locations.country')),
            ],
            options={
                'verbose_name': 'Country VAT Rate',
                'verbose_name_plural': 'Country VAT Rates',
                'ordering': ('country',),
            },
        ),
    ]
