# Generated by Django 4.2.14 on 2024-10-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_experiences_location_good_to_know_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='experiences',
        ),
    ]
