# Generated by Django 4.2.14 on 2024-12-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_sublocation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2',
            field=models.CharField(help_text='\n            ISO 3166-1 Alpha-2 Code.\n            Check possible values here:\n\n            https://www.countrycodeplanet.com/\n        ', max_length=2, primary_key=True, serialize=False, verbose_name='ISO alpha-2'),
        ),
        migrations.AlterField(
            model_name='country',
            name='alpha3',
            field=models.CharField(help_text='\n            ISO 3166-1 Alpha-3 Code\n            Check possible values here:\n\n            https://www.countrycodeplanet.com/\n        ', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='numcode',
            field=models.PositiveSmallIntegerField(help_text='\n            ISO 3166-1 Numeric Code\n            Check possible values here:\n\n            https://www.countrycodeplanet.com/\n        ', null=True, verbose_name='ISO numeric'),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone',
            field=models.CharField(help_text='\n            Phone Indicative\n            Check possible values here:\n\n            https://www.countrycodeplanet.com/\n        ', max_length=3),
        ),
    ]
