# Generated by Django 4.2.14 on 2025-02-18 20:25

from django.db import migrations, models


def populate_cities(apps, schema_editor):
    Location = apps.get_model('locations', 'Location')
    for location in Location.objects.all():
        if not location.city:
            continue
        location.cities.add(location.city)
        location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='destinations', to='locations.city'),
        ),
        migrations.RunPython(populate_cities, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
    ]
