# Generated by Django 4.2.14 on 2025-02-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='country_banners/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='location',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='location_banners/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='sublocation',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='sublocation_banner/', verbose_name='Banner'),
        ),
    ]
