# Generated by Django 4.2.14 on 2024-10-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_article_updated_at_alter_article_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicImage',
        ),
    ]
