# Generated by Django 4.2.14 on 2024-10-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_article_banner_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
