# Generated by Django 4.2.14 on 2024-11-19 16:10

# import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_article_author'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='topic',
        #     name='content',
        #     field=ckeditor.fields.RichTextField(),
        # ),
    ]
