# Generated by Django 4.2.14 on 2024-11-19 16:31

# import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_topic_content'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='topic',
        #     name='content',
        #     field=ckeditor_uploader.fields.RichTextUploadingField(),
        # ),
    ]
