# Generated by Django 4.2.14 on 2024-11-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('beautiful_destinations', 'Beautiful Destinations'), ('holiday_intel', 'Holiday Intel'), ('exploring_our_homes', 'Exploring Our Homes'), ('city_guides', 'City Guides'), ('our_catalogs', 'Our Catalogs'), ('about_tripwix', 'About Tripwix')], max_length=50, null=True),
        ),
    ]
