# Generated by Django 4.2.14 on 2024-11-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_article_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
    ]
