# Generated by Django 4.2.14 on 2024-11-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_article_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('amazing_art_awards', 'Amazing Art Awards'), ('awesome_adventures', 'Awesome Adventures'), ('beach_breaks', 'Beach Breaks'), ('cultural_customs', 'Cultural Customs'), ('european_escapes', 'European Escapes'), ('fabulous_festivals', 'Fabulous Festivals'), ('family_fun', 'Family Fun'), ('family_time', 'Family Time'), ('golf_getaways', 'Golf Getaways'), ('guest_reviews', 'Guest Reviews'), ('incredible_italy', 'Incredible Italy'), ('local_crafts', 'Local Crafts'), ('local_experiences', 'Local Experiences'), ('luxury_real_estate', 'Luxury Real Estate'), ('luxury_wellness_travel', 'Luxury Wellness Travel'), ('marvelous_mexico', 'Marvelous Mexico'), ('music_and_nightlife', 'Music and Nightlife'), ('natural_wonders', 'Natural Wonders'), ('party_places_and_events', 'Party Places and Events'), ('pretty_portugal', 'Pretty Portugal'), ('property_management', 'Property Management'), ('regional_recipes', 'Regional Recipes'), ('relaxation', 'Relaxation'), ('relaxing_retreats', 'Relaxing Retreats'), ('remarkable_restaurants', 'Remarkable Restaurants'), ('riverboat_cruise', 'Riverboat Cruise'), ('romantic_respites', 'Romantic Respites'), ('sunny_spain', 'Sunny Spain'), ('superb_shopping', 'Superb Shopping'), ('tempting_turkey', 'Tempting Turkey'), ('travel_tips', 'Travel Tips'), ('whimsical_weddings', 'Whimsical Weddings')], max_length=50, null=True),
        ),
    ]
