# Generated by Django 4.2.14 on 2025-02-24 13:10

from django.db import migrations, models
from django.utils.text import slugify


def create_slugs(apps, schema_editor):
    Article = apps.get_model('blogs', 'Article')
    for article in Article.objects.all():
        article.slug = slugify(article.title)
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(create_slugs, migrations.RunPython.noop),
    ]
