# Generated by Django 4.2.14 on 2025-02-24 13:15

from django.db import migrations, models
from django.utils.text import slugify


def recreate_article_slugs(apps, schema_editor):
    Article = apps.get_model('blogs', 'Article')
    for article in Article.objects.all():
        article.slug = slugify(article.title)
        if Article.objects.filter(slug=article.slug).count() > 1:
            article.slug += f'-{article.id}'
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_article_slug'),
    ]

    operations = [
        migrations.RunPython(recreate_article_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]

