# Generated by Django 4.2.14 on 2025-02-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_websiteuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('token', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
