# Generated by Django 4.2.15 on 2024-08-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0025_property_hostify_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hostify_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('reservation_status', models.CharField(choices=[('no_status', 'No Status'), ('confirmed', 'Confirmed'), ('accepted', 'Accepted'), ('pending', 'Pending'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('awaiting_payment', 'Awaiting Payment'), ('moved', 'Moved'), ('extended', 'Extended'), ('edited', 'Edited'), ('retracted', 'Retracted'), ('inquiry', 'Inquiry'), ('declined_inq', 'Declined Inquiry'), ('preapproved', 'Preapproved'), ('offer', 'Offer'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('timedout', 'Timed Out'), ('not_possible', 'Not Possible'), ('new', 'New'), ('deleted', 'Deleted')], default='no_status', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'date')},
            },
        ),
    ]
