# Generated by Django 4.2.14 on 2024-09-30 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_propertyratingscore'),
        ('hostify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycalendar',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostify_calendars', to='properties.property'),
        ),
    ]
