# Generated by Django 4.2.14 on 2024-10-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostify', '0002_alter_propertycalendar_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycalendar',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
