# Generated by Django 4.2.14 on 2024-09-24 10:07

import photologue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0004_alter_slide_image_alter_slide_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='cta_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slide',
            name='cta_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, help_text='JSON data for custom slide types'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(
                blank=True, help_text='Max size: 10MB', null=True, upload_to=photologue.models.get_storage_path
            ),
        ),
    ]
