# Generated by Django 4.2.14 on 2024-11-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0005_slide_cta_text_slide_cta_url_slide_extra_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
