# Generated by Django 4.2.5 on 2023-09-23 02:55

import django.db.models.deletion
import django.utils.timezone
import photologue.models
from django.db import migrations, models

import apps.media.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0013_alter_watermark_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=photologue.models.get_storage_path, verbose_name='image')),
                ('date_taken', models.DateTimeField(blank=True, help_text='Date image was taken; is obtained from the image EXIF data.', null=True, verbose_name='date taken')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='view count')),
                ('crop_from', models.CharField(blank=True, choices=[('top', 'Top'), ('right', 'Right'), ('bottom', 'Bottom'), ('left', 'Left'), ('center', 'Center (Default)')], default='center', max_length=10, verbose_name='crop from')),
                ('caption', models.CharField(blank=True, max_length=128, null=True, verbose_name='caption')),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='photologue.photoeffect', verbose_name='effect')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'db_table': 'media_photo',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(unique=True, verbose_name='Url / Handle')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('publication_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the gallery should go live.', verbose_name='publication date')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this gallery should be treated as active. Unselect this instead of deleting articles.', verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, help_text='Designates whether this gallery should be treated as featured.', verbose_name='featured')),
                ('is_public', models.BooleanField(default=True, help_text='Public galleries will be displayed in the default views.', verbose_name='is public')),
                ('enable_comments', models.BooleanField(default=False, verbose_name='enable comments')),
                ('photos', apps.media.fields.MediaPhotoField(blank=True, related_name='media_gallery', to='media.mediaphoto', verbose_name='photos')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'db_table': 'media_gallery',
            },
        ),
    ]
