# Generated by Django 4.2.14 on 2024-09-13 11:40

import django.contrib.postgres.indexes
import hashid_field.field
from django.db import migrations, models

import apps.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('id', hashid_field.field.BigHashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=13, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('file_object', models.FileField(upload_to='documents', verbose_name='File')),
                ('i18n', apps.core.fields.TranslationField(fields=('title', 'description'), required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='media_media_i18n_b2f577_gin')],
            },
        ),
    ]
