# Generated by Django 4.2.14 on 2024-12-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file for this page.', null=True, upload_to='videos', verbose_name='Video'),
        ),
    ]
