# Generated by Django 4.2.14 on 2024-12-12 10:07

from django.db import migrations, models

import apps.pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file for this page.', null=True, upload_to='videos', validators=[apps.pages.models.validate_video_file], verbose_name='Video'),
        ),
    ]
