# Generated by Django 4.2.13 on 2024-07-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipedrive_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('pipedrive_metadata', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['pipedrive_id'], name='organization_pipedrive_id_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipedrive_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('pipedrive_metadata', models.JSONField()),
                (
                    'organization',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipedrive.organization'),
                ),
            ],
            options={
                'indexes': [models.Index(fields=['pipedrive_id'], name='deal_pipedrive_id_idx')],
            },
        ),
    ]
