# Generated by Django 4.2.13 on 2024-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipedrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deal_offset',
            field=models.IntegerField(default=0),
        ),
    ]
