# Generated by Django 4.2.13 on 2024-07-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipedrive', '0003_alter_organization_address_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='deal',
            name='pipedrive_metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
