# Generated by Django 4.2.14 on 2024-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipedrive', '0004_alter_deal_currency_alter_deal_pipedrive_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipedrive_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('pipedrive_metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
