# Generated by Django 4.2.14 on 2024-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipedrive', '0007_person_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='number_of_guests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='property_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
