# Generated by Django 4.2.14 on 2024-10-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipedrive', '0008_deal_checkin_date_deal_checkout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipedrive.organization'),
        ),
    ]
