# Generated by Django 4.2.14 on 2024-10-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipedrive', '0009_alter_deal_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='budget',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deal',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='flexible_dates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='lead_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='property_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='property_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deal',
            name='requested_nights',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipedrive.organization'),
        ),
    ]
